# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Publish vpdq to pypi

on:
  push:
    branches:
      - main
    paths:
      - "vpdq/version.txt"

defaults:
  run:
    working-directory: vpdq

jobs:
  publish:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi-test
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev pkg-config cmake ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev

      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r packaging-requirements.txt
          python -m pip list

      - name: Package
        run: |
          python -m build --sdist

      - name: Ensure packaged build runs
        run: |
          python -m pip install dist/vpdq*.tar.gz
          python -m pip list
          python -c "import vpdq; print(dir(vpdq))"

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: vpdq/dist

      # From https://packaging.python.org/en/latest/guides/using-testpypi/#using-testpypi-with-pip
      - name: Test installing the published Test PyPI distribution package
        run: |
          pip list
          pip uninstall -y -r <(pip freeze)
          pip list
          python -m pip install --index-url https://test.pypi.org/simple/ vpdq
          pip list
          python -c "import vpdq; print(dir(vpdq))"
          python -m pip install pytest
          python -m pytest
